### PR TITLE
Remove stack defaults ConfigMap

### PR DESCRIPTION
**Pull request by ianpartridge**
I think the plan is for this YAML to be generated and applied by `appsody deploy` instead.

CC: @seabaylea @arthurdm

### CODE REVIEW

**Comment by arthurdm** [comment]
hey @ianpartridge - I think we should still keep this default ConfigMap, since this operator could be used even on its own independent of appsody or kabanero.  

The `stack_default.yaml` that each stack / collection has can (and will) certainly override the default values that comes with the out-of-the-box operator.  thoughts?

**Comment by ianpartridge** [comment]
Build failed because my fork does not have Docker credentials.  I don't think I should be required to have those credentials to run a PR build so that seems like a problem with the CI system, not my changes.

**Comment by ianpartridge** [comment]
Doesn't that mean if a new appsody stack is added we need to teach the operator about it?

**Comment by arthurdm** [comment]
If a stack is used during deployment and a match is not found in the ConfigMap then we just default to the `generic` defaults.  So when adding a new stack the best practice would be to patch the ConfigMap with that stack's key/value - just like patching existing stacks.

**Comment by ianpartridge** [comment]
Hmm I think I'm missing something.

> I think we should still keep this default ConfigMap, since this operator could be used even on its own independent of appsody or kabanero.

How/why could the `appsody-operator` be used independently of Appsody?

**Comment by arthurdm** [comment]
Anybody can install this operator and run their own application image without having an Appsody Stack.

**Comment by ianpartridge** [comment]
OK I need to re-wire my brain on all this.

(The CI failure is still worth fixing I think as it blocks external contributions).

**Pull request closed without merging**
